// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using prjVisaSupplier.Models;

namespace prjVisaSupplier.Models
{
    public partial class dbTravalPlatformContext
    {

        [DbFunction("GetOrderID_V", "dbo")]
        public static string GetOrderID_V()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
