// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjVisaSupplier.Models;

[Table("tCCompanyInfo")]
public partial class TCcompanyInfo
{
    [Key]
    [Column("fId")]
    public int FId { get; set; }

    [Column("fType")]
    [StringLength(50)]
    public string FType { get; set; }

    [Column("fCompanyName")]
    [StringLength(50)]
    public string FCompanyName { get; set; }

    [Column("fLanguage")]
    [StringLength(50)]
    public string FLanguage { get; set; }

    [Column("fCountry")]
    [StringLength(50)]
    public string FCountry { get; set; }

    [Column("fCity")]
    [StringLength(50)]
    public string FCity { get; set; }

    [Column("fPostalCode")]
    public int? FPostalCode { get; set; }

    [Column("fAddress")]
    [StringLength(50)]
    public string FAddress { get; set; }

    [Column("fPhoneCountryCode")]
    [StringLength(50)]
    public string FPhoneCountryCode { get; set; }

    [Column("fPhone")]
    [StringLength(50)]
    public string FPhone { get; set; }

    [Column("fUrl")]
    [StringLength(50)]
    public string FUrl { get; set; }

    [Column("fNameOfPersonInCharge")]
    [StringLength(50)]
    public string FNameOfPersonInCharge { get; set; }

    [Column("fCertificatePath")]
    public string FCertificatePath { get; set; }

    [Column("fContactName")]
    [StringLength(50)]
    public string FContactName { get; set; }

    [Column("fContactPosition")]
    [StringLength(50)]
    public string FContactPosition { get; set; }

    [Column("fContactEmail")]
    [StringLength(50)]
    public string FContactEmail { get; set; }

    [Column("fPassword")]
    [StringLength(50)]
    public string FPassword { get; set; }

    [Column("fContactPhoneCountryCode")]
    [StringLength(50)]
    public string FContactPhoneCountryCode { get; set; }

    [Column("fContactPhone")]
    [StringLength(50)]
    public string FContactPhone { get; set; }

    [Column("fContactTimeZone")]
    public int? FContactTimeZone { get; set; }

    [Column("fIsChecked")]
    [StringLength(50)]
    public string FIsChecked { get; set; }

    [Column("fCheckDate")]
    [StringLength(50)]
    public string FCheckDate { get; set; }

    [Column("fIsInCooperation")]
    [StringLength(50)]
    public string FIsInCooperation { get; set; }

    [Column("fLogo")]
    public byte[] FLogo { get; set; }

    [InverseProperty("FSupplier")]
    public virtual ICollection<TVproduct> TVproducts { get; set; } = new List<TVproduct>();
}