// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjVisaSupplier.Models;

[Table("tCustomer")]
public partial class TCustomer
{
    [Key]
    [Column("fCustomerId")]
    public int FCustomerId { get; set; }

    [Column("fName")]
    [StringLength(50)]
    public string FName { get; set; }

    [Column("fPassword")]
    [StringLength(50)]
    public string FPassword { get; set; }

    [Column("fEmail")]
    [StringLength(50)]
    public string FEmail { get; set; }

    [Column("fGender")]
    [StringLength(50)]
    public string FGender { get; set; }

    [Column("fBirth")]
    [StringLength(50)]
    public string FBirth { get; set; }

    [Column("fIdentityNumber")]
    [StringLength(50)]
    public string FIdentityNumber { get; set; }

    [Column("fPhone")]
    [StringLength(50)]
    public string FPhone { get; set; }

    [Column("fAddress")]
    [StringLength(50)]
    public string FAddress { get; set; }

    [Column("fLevelId")]
    public int? FLevelId { get; set; }

    [Column("fPoint")]
    public int? FPoint { get; set; }

    [Column("fRegisterDate")]
    [StringLength(50)]
    public string FRegisterDate { get; set; }

    [Column("fImagePath")]
    [StringLength(50)]
    public string FImagePath { get; set; }

    [Column("fIsCheck")]
    public bool? FIsCheck { get; set; }

    [InverseProperty("FCustomer")]
    public virtual ICollection<TVorder> TVorders { get; set; } = new List<TVorder>();
}