// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjVisaSupplier.Models;

[Table("tVCountry")]
public partial class TVcountry
{
    [Key]
    [Column("fId")]
    public int FId { get; set; }

    [Required]
    [Column("fRegion")]
    [StringLength(50)]
    public string FRegion { get; set; }

    [Required]
    [Column("fCountry")]
    [StringLength(50)]
    public string FCountry { get; set; }

    [InverseProperty("FCountry")]
    public virtual ICollection<TVproduct> TVproducts { get; set; } = new List<TVproduct>();
}