// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjVisaSupplier.Models;

[Table("tVOrder")]
public partial class TVorder
{
    [Key]
    [Column("fId")]
    public int FId { get; set; }

    [Column("fOrderId")]
    [StringLength(50)]
    public string FOrderId { get; set; }

    [Column("fProductId")]
    public int FProductId { get; set; }

    [Column("fCustomerId")]
    public int FCustomerId { get; set; }

    [Column("fPrice", TypeName = "money")]
    public decimal? FPrice { get; set; }

    [Column("fQuantity")]
    public int FQuantity { get; set; }

    [Column("fDepartureDate")]
    [StringLength(50)]
    public string FDepartureDate { get; set; }

    [Column("fForPickupOrDeliveryAddress")]
    [StringLength(50)]
    public string FForPickupOrDeliveryAddress { get; set; }

    [Column("fInterviewReminder")]
    public bool? FInterviewReminder { get; set; }

    [Column("fEvaluate")]
    public int? FEvaluate { get; set; }

    [Column("fMemo")]
    [StringLength(50)]
    public string FMemo { get; set; }

    [Column("fStatusId")]
    public int? FStatusId { get; set; }

    [Column("fCouponId")]
    public int? FCouponId { get; set; }

    [ForeignKey("FCouponId")]
    [InverseProperty("TVorders")]
    public virtual TCouponList FCoupon { get; set; }

    [ForeignKey("FCustomerId")]
    [InverseProperty("TVorders")]
    public virtual TCustomer FCustomer { get; set; }

    [ForeignKey("FProductId")]
    [InverseProperty("TVorders")]
    public virtual TVproduct FProduct { get; set; }

    [ForeignKey("FStatusId")]
    [InverseProperty("TVorders")]
    public virtual TVorderStatus FStatus { get; set; }

    [InverseProperty("FOrder")]
    public virtual ICollection<TVtravelerInfo> TVtravelerInfos { get; set; } = new List<TVtravelerInfo>();
}