// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjVisaSupplier.Models;

[Table("tVOrderStatus")]
public partial class TVorderStatus
{
    [Key]
    [Column("fId")]
    public int FId { get; set; }

    [Column("fVOrderStatus")]
    [StringLength(50)]
    public string FVorderStatus { get; set; }

    [InverseProperty("FStatus")]
    public virtual ICollection<TVorder> TVorders { get; set; } = new List<TVorder>();
}