// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjVisaSupplier.Models;

[Table("tVProduct")]
public partial class TVproduct
{
    [Key]
    [Column("fId")]
    public int FId { get; set; }

    [Column("fCountryId")]
    public int FCountryId { get; set; }

    [Column("fSupplierId")]
    public int FSupplierId { get; set; }

    [Required]
    [Column("fName")]
    [StringLength(50)]
    public string FName { get; set; }

    [Column("fNewOrLost")]
    public bool FNewOrLost { get; set; }

    [Column("fInterviewRequirement")]
    public bool FInterviewRequirement { get; set; }

    [Column("fEntityOrElectronic")]
    public bool FEntityOrElectronic { get; set; }

    [Column("fProcessingTimeId")]
    public int FProcessingTimeId { get; set; }

    [Column("fValidityPeriodId")]
    public int FValidityPeriodId { get; set; }

    [Column("fLengthOfStayId")]
    public int FLengthOfStayId { get; set; }

    [Column("fPrice", TypeName = "money")]
    public decimal FPrice { get; set; }

    [Column("fEnabled")]
    public bool FEnabled { get; set; }

    [ForeignKey("FCountryId")]
    [InverseProperty("TVproducts")]
    public virtual TVcountry FCountry { get; set; }

    [ForeignKey("FLengthOfStayId")]
    [InverseProperty("TVproducts")]
    public virtual TVlengthOfStay FLengthOfStay { get; set; }

    [ForeignKey("FProcessingTimeId")]
    [InverseProperty("TVproducts")]
    public virtual TVprocessingTime FProcessingTime { get; set; }

    [ForeignKey("FSupplierId")]
    [InverseProperty("TVproducts")]
    public virtual TCcompanyInfo FSupplier { get; set; }

    [ForeignKey("FValidityPeriodId")]
    [InverseProperty("TVproducts")]
    public virtual TVvalidityPeriod FValidityPeriod { get; set; }

    [InverseProperty("FProduct")]
    public virtual ICollection<TVorder> TVorders { get; set; } = new List<TVorder>();

    [InverseProperty("FProduct")]
    public virtual ICollection<TVproductFormsRequired> TVproductFormsRequireds { get; set; } = new List<TVproductFormsRequired>();
}