// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjVisaSupplier.Models;

[Table("tVProcessingTime")]
public partial class TVprocessingTime
{
    [Key]
    [Column("fId")]
    public int FId { get; set; }

    [Column("fProcessingTime")]
    public int FProcessingTime { get; set; }

    [InverseProperty("FProcessingTime")]
    public virtual ICollection<TVproduct> TVproducts { get; set; } = new List<TVproduct>();
}