// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjVisaSupplier.Models;

[Table("tVTravelerInfo")]
public partial class TVtravelerInfo
{
    [Key]
    [Column("fId")]
    public int FId { get; set; }

    [Column("fOrderId")]
    public int FOrderId { get; set; }

    [Column("fName")]
    [StringLength(50)]
    public string FName { get; set; }

    [Column("fGender")]
    public bool? FGender { get; set; }

    [Column("fBirthDate")]
    [StringLength(50)]
    public string FBirthDate { get; set; }

    [ForeignKey("FOrderId")]
    [InverseProperty("TVtravelerInfos")]
    public virtual TVorder FOrder { get; set; }
}