// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjVisaSupplier.Models;

[Table("tVValidityPeriod")]
public partial class TVvalidityPeriod
{
    [Key]
    [Column("fId")]
    public int FId { get; set; }

    [Required]
    [Column("fValidityPeriod")]
    [StringLength(50)]
    public string FValidityPeriod { get; set; }

    [InverseProperty("FValidityPeriod")]
    public virtual ICollection<TVproduct> TVproducts { get; set; } = new List<TVproduct>();
}