// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjVisaSupplier.Models;

[Keyless]
public partial class VVorderView
{
    [Column("fId")]
    public int FId { get; set; }

    [StringLength(50)]
    public string 編號 { get; set; }

    [StringLength(50)]
    public string 客戶名稱 { get; set; }

    [Required]
    [StringLength(50)]
    public string 商品名稱 { get; set; }

    [StringLength(50)]
    public string 廠商 { get; set; }

    [StringLength(10)]
    public string 訂單日期 { get; set; }

    [Column(TypeName = "money")]
    public decimal? 單價 { get; set; }

    public int 數量 { get; set; }

    [StringLength(50)]
    public string 優惠券 { get; set; }

    [Column(TypeName = "money")]
    public decimal? 折扣金額 { get; set; }

    [Column(TypeName = "money")]
    public decimal? 總價 { get; set; }

    public bool? 面試提醒 { get; set; }

    [StringLength(50)]
    public string 自取或配送 { get; set; }

    public int? 評價 { get; set; }

    [StringLength(50)]
    public string 訂單狀態 { get; set; }

    [StringLength(50)]
    public string 預計出國日期 { get; set; }

    public bool 是否需面試 { get; set; }

    public bool 實體或電子簽 { get; set; }

    [StringLength(50)]
    public string 備註 { get; set; }
}