// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace prjVisaSupplier.Models;

[Keyless]
public partial class VVproductView
{
    public int 商品編號 { get; set; }

    [Required]
    [StringLength(50)]
    public string 商品名稱 { get; set; }

    [StringLength(50)]
    public string 廠商 { get; set; }

    [Required]
    [StringLength(50)]
    public string 地區 { get; set; }

    [Required]
    [StringLength(50)]
    public string 國家 { get; set; }

    public bool 新辦or遺失 { get; set; }

    public bool 實體or電子簽 { get; set; }

    public int 辦理耗時天數 { get; set; }

    [Required]
    [StringLength(50)]
    public string 效期 { get; set; }

    [Required]
    [StringLength(50)]
    public string 可留天數 { get; set; }

    [Column(TypeName = "money")]
    public decimal 價格 { get; set; }

    public bool 啟用狀態 { get; set; }
}